   plugins {
    id 'java'
}

group = 'cn.zhangyis'
version = '1.0-SNAPSHOT'

allprojects {
    apply plugin: 'java'

    group = 'cn.zhangyis'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenLocal()
//        maven { url = 'https://maven.aliyun.com/repository/jcenter' }
//        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots/' }
//        maven { url = "https://plugins.gradle.org/m2/" }
        mavenCentral()
    }

    dependencies {
        compileOnly 'org.projectlombok:lombok:1.18.30'
        annotationProcessor 'org.projectlombok:lombok:1.18.30'
        testCompileOnly 'org.projectlombok:lombok:1.18.30'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
        // https://mvnrepository.com/artifact/com.google.guava/guava
        implementation 'com.google.guava:guava:33.0.0-jre'
// https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
        implementation 'org.apache.commons:commons-lang3:3.14.0'
// https://mvnrepository.com/artifact/commons-io/commons-io
        implementation 'commons-io:commons-io:2.15.1'
// https://mvnrepository.com/artifact/cn.hutool/hutool-all
        implementation 'cn.hutool:hutool-all:5.8.24'
        // https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
// https://mvnrepository.com/artifact/org.apache.commons/commons-collections4
        implementation 'org.apache.commons:commons-collections4:4.5.0'
        testImplementation platform("org.junit:junit-bom:5.10.2")
        testImplementation "org.junit.jupiter:junit-jupiter"
        testRuntimeOnly  "org.junit.platform:junit-platform-launcher"
        implementation 'org.slf4j:slf4j-api:1.7.32'  // 添加 SLF4J API

    }

    test {
        useJUnitPlatform()
    }

    tasks.withType(JavaCompile) {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}


java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = '21'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaExec){
    jvmArgs = ['-Xmx512m', '-Dfile.encoding=UTF-8', '-Dsun.stdout.encoding=UTF-8','-Dsun.stderr.encoding=UTF-8']
}
